// <auto-generated />
using Hotel_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250214225017_initial-database")]
    partial class initialdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_API.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherImages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A luxurious resort located in the heart of the Maldives, offering breathtaking views and world-class amenities.",
                            HomeImage = "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                            Location = "Maldives",
                            Name = "Luxury Paradise Resort",
                            OtherImages = "https://images.unsplash.com/photo-1564501049412-61c2a3083791,https://images.unsplash.com/photo-1566073771259-6a8506099945,https://images.unsplash.com/photo-1618773928121-c32242e63f39,https://images.unsplash.com/photo-1564501049412-61c2a3083791,https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Price = 450.0,
                            Rating = 5,
                            Services = "Spa,fas fa-spa;Pool,fas fa-swimming-pool;Gym,fas fa-dumbbell;Free Wi-Fi,fas fa-wifi;Restaurant,fas fa-utensils"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A serene beachfront hotel with stunning sunset views and a relaxing atmosphere.",
                            HomeImage = "https://images.unsplash.com/photo-1549989476-69a92fa57c36",
                            Location = "Bali, Indonesia",
                            Name = "Sunset Beach Hotel",
                            OtherImages = "https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36",
                            Price = 350.0,
                            Rating = 4,
                            Services = "Beach Access,fas fa-umbrella-beach;Pool,fas fa-swimming-pool;Bar,fas fa-cocktail;Free Wi-Fi,fas fa-wifi;Restaurant,fas fa-utensils"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A cozy lodge nestled in the Swiss Alps, perfect for winter sports and relaxation.",
                            HomeImage = "https://images.unsplash.com/photo-1519681393784-d120267933ba",
                            Location = "Swiss Alps",
                            Name = "Mountain View Lodge",
                            OtherImages = "https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba",
                            Price = 300.0,
                            Rating = 4,
                            Services = "Skiing,fas fa-skiing;Spa,fas fa-spa;Restaurant,fas fa-utensils;Free Wi-Fi,fas fa-wifi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A modern hotel located in the heart of New York City, ideal for business and leisure travelers.",
                            HomeImage = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a",
                            Location = "New York, USA",
                            Name = "City Central Hotel",
                            OtherImages = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a",
                            Price = 250.0,
                            Rating = 3,
                            Services = "Gym,fas fa-dumbbell;Free Wi-Fi,fas fa-wifi;Restaurant,fas fa-utensils;Conference Rooms,fas fa-users"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A luxurious resort in the middle of the desert, offering a unique blend of tradition and modernity.",
                            HomeImage = "https://images.unsplash.com/photo-1518684079-3c830dcef090",
                            Location = "Dubai, UAE",
                            Name = "Desert Oasis Resort",
                            OtherImages = "https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090",
                            Price = 500.0,
                            Rating = 5,
                            Services = "Pool,fas fa-swimming-pool;Spa,fas fa-spa;Free Wi-Fi,fas fa-wifi;Restaurant,fas fa-utensils;Camel Riding,fas fa-horse"
                        });
                });

            modelBuilder.Entity("Hotel_API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferPresentage")
                        .HasColumnType("int");

                    b.Property<double>("OldPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RoomDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedType = "1 king bed",
                            Days = 5,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 1,
                            Images = "https://images.unsplash.com/photo-1618773928121-c32242e63f39,https://images.unsplash.com/photo-1564501049412-61c2a3083791,https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            OfferPresentage = 10,
                            OldPrice = 12000.0,
                            Price = 10000.0,
                            RoomDescription = "A spacious and comfortable room with modern amenities.",
                            RoomNumber = "Room 1",
                            RoomSize = "50 m²",
                            RoomType = "One Bedroom Apartment",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "Sea view"
                        },
                        new
                        {
                            Id = 2,
                            BedType = "2 twin beds",
                            Days = 7,
                            Facilities = "Walk-in closet;Tea/Coffee maker;Kitchenette;Soundproof;Dining area;Washing machine",
                            HotelId = 2,
                            Images = "https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36,https://images.unsplash.com/photo-1549989476-69a92fa57c36",
                            OfferPresentage = 15,
                            OldPrice = 18000.0,
                            Price = 15000.0,
                            RoomDescription = "A luxurious apartment with a stunning view and excellent facilities.",
                            RoomNumber = "Room 2",
                            RoomSize = "80 m²",
                            RoomType = "Two-Bedroom Apartment",
                            Services = "Free Wifi,fas fa-wifi;Kitchenette,fas fa-utensils;Jacuzzi,fas fa-hot-tub;Safe,fas fa-lock;Work desk,fas fa-laptop",
                            View = "Garden view"
                        },
                        new
                        {
                            Id = 3,
                            BedType = "1 king bed",
                            Days = 10,
                            Facilities = "Fireplace;Patio;Flat-screen TV;Safe;Dining area;Dryer",
                            HotelId = 3,
                            Images = "https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba,https://images.unsplash.com/photo-1519681393784-d120267933ba",
                            OfferPresentage = 20,
                            OldPrice = 30000.0,
                            Price = 25000.0,
                            RoomDescription = "A spacious villa with private amenities and breathtaking views.",
                            RoomNumber = "Room 3",
                            RoomSize = "120 m²",
                            RoomType = "Stand Alone Villa",
                            Services = "Balcony,fas fa-umbrella-beach;Soundproof,fas fa-volume-mute;Fireplace,fas fa-fire;Ironing facilities,fas fa-iron;Sitting area,fas fa-couch",
                            View = "Mountain view"
                        },
                        new
                        {
                            Id = 4,
                            BedType = "1 queen bed",
                            Days = 8,
                            Facilities = "Flat-screen TV;Tea/Coffee maker;Ironing facilities;Soundproof;Patio;Dryer",
                            HotelId = 4,
                            Images = "https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a,https://images.unsplash.com/photo-1499856871958-5b9627545d1a",
                            OfferPresentage = 25,
                            OldPrice = 25000.0,
                            Price = 20000.0,
                            RoomDescription = "A deluxe suite with all modern amenities for a comfortable stay.",
                            RoomNumber = "Room 4",
                            RoomSize = "70 m²",
                            RoomType = "Deluxe Suite",
                            Services = "Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Safe,fas fa-lock;Jacuzzi,fas fa-hot-tub;Work desk,fas fa-laptop",
                            View = "City view"
                        },
                        new
                        {
                            Id = 5,
                            BedType = "2 queen beds",
                            Days = 6,
                            Facilities = "Walk-in closet;Flat-screen TV;Safe;Fireplace;Air conditioning;Washing machine",
                            HotelId = 5,
                            Images = "https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090,https://images.unsplash.com/photo-1518684079-3c830dcef090",
                            OfferPresentage = 5,
                            OldPrice = 16000.0,
                            Price = 13000.0,
                            RoomDescription = "An executive room perfect for business travelers and leisure.",
                            RoomNumber = "Room 5",
                            RoomSize = "60 m²",
                            RoomType = "Executive Room",
                            Services = "Free Wifi,fas fa-wifi;Balcony,fas fa-umbrella-beach;Kitchenette,fas fa-utensils;Dining area,fas fa-utensils;Sitting area,fas fa-couch",
                            View = "Pool view"
                        },
                        new
                        {
                            Id = 6,
                            BedType = "1 king bed",
                            Days = 9,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 2,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 12,
                            OldPrice = 18000.0,
                            Price = 16000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 6",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 7,
                            BedType = "1 king bed",
                            Days = 10,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 3,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 14,
                            OldPrice = 19000.0,
                            Price = 17000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 7",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 8,
                            BedType = "1 king bed",
                            Days = 11,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 4,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 16,
                            OldPrice = 20000.0,
                            Price = 18000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 8",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 9,
                            BedType = "1 king bed",
                            Days = 12,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 5,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 18,
                            OldPrice = 21000.0,
                            Price = 19000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 9",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 10,
                            BedType = "1 king bed",
                            Days = 13,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 1,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 20,
                            OldPrice = 22000.0,
                            Price = 20000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 10",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 11,
                            BedType = "1 king bed",
                            Days = 14,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 2,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 22,
                            OldPrice = 23000.0,
                            Price = 21000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 11",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 12,
                            BedType = "1 king bed",
                            Days = 15,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 3,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 24,
                            OldPrice = 24000.0,
                            Price = 22000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 12",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 13,
                            BedType = "1 king bed",
                            Days = 16,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 4,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 26,
                            OldPrice = 25000.0,
                            Price = 23000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 13",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 14,
                            BedType = "1 king bed",
                            Days = 17,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 5,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 28,
                            OldPrice = 26000.0,
                            Price = 24000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 14",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        },
                        new
                        {
                            Id = 15,
                            BedType = "1 king bed",
                            Days = 18,
                            Facilities = "Balcony;Air conditioning;Private bathroom;Flat-screen TV;Minibar;Free Wifi",
                            HotelId = 1,
                            Images = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            OfferPresentage = 30,
                            OldPrice = 27000.0,
                            Price = 25000.0,
                            RoomDescription = "A comfortable room with essential amenities.",
                            RoomNumber = "Room 15",
                            RoomSize = "50 m²",
                            RoomType = "Standard Room",
                            Services = "Free Wifi,fas fa-wifi;Air Conditioning,fas fa-snowflake;Private Bathroom,fas fa-bath;Minibar,fas fa-wine-glass-alt;Flat-screen TV,fas fa-tv",
                            View = "City view"
                        });
                });

            modelBuilder.Entity("Hotel_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SpokenLanguage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Street, NY",
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "hashedpassword1",
                            Phone = "1234567890",
                            SpokenLanguage = "English"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Street, LA",
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "hashedpassword2",
                            Phone = "0987654321",
                            SpokenLanguage = "French"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Street, TX",
                            Email = "alice@example.com",
                            Name = "Alice Brown",
                            Password = "hashedpassword3",
                            Phone = "1112223333",
                            SpokenLanguage = "Spanish"
                        });
                });

            modelBuilder.Entity("Hotel_API.Models.Room", b =>
                {
                    b.HasOne("Hotel_API.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_API.Models.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel_API.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel_API.Models.User", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
